FROM python:3.12-slim

WORKDIR /worker

COPY pyproject.toml  ./

COPY wait-for-it.sh ./

RUN chmod +x ./wait-for-it.sh

RUN pip install .[consumer]

COPY worker .

CMD ["python3" ,"-m", "kafka_consumer"]